#!/usr/bin/env python3

import argparse, re, time, hmac, pyotp, hashlib, struct, os, base64
from hashlib import sha1


KEY_FILE = "ft_otp.key"
SALT = b"We Are All Mad Here !"
ITERATIONS = 100000
ENCRYPTION_KEY_LENGTH = 32
OTP_DIGITS = 6


def encrypt_key(content):
    key = content.encode('utf-8')
    salt = os.urandom(16)
    key_hash = hashlib.sha256(salt + key).digest()
    mac = hmac.new(key_hash, salt, hashlib.sha256).digest()
    return base64.b64encode(salt + mac + key).decode('utf-8')


def decrypt_key(encrypted_key):
    encrypted_bytes = base64.b64decode(encrypted_key)

    salt = encrypted_bytes[:16]
    mac = encrypted_bytes[16:48]
    key = encrypted_bytes[48:]

    key_hash = hashlib.sha256(salt + key).digest()
    calculated_mac = hmac.new(key_hash, salt, hashlib.sha256).digest()

    if calculated_mac != mac:
        raise ValueError("Decryption failed: Integrity check failed")

    return(key.decode('utf-8'))


def check_hexa(content):
    pattern = r'^\A(?:[0-9A-Fa-f]{2}\s?)+\Z'
    match = re.match(pattern, content)
    key_len = len(content)

    if match and key_len == 64:
        return True
    else:
        print("Error: Key must be 64 hexadecimal characters")
        return False


def parse_file(file):
    try:
        with open(file, 'r') as f:
            content = f.read().strip()
            if check_hexa(content) is True:
                return encrypt_key(content)
            else:
                return None
    except FileNotFoundError:
        print(f"File {file} can't be opened")


def ft_generate(key):
	now = int(time.time())
	alive = 30
	time_step = now // alive
	time_bytes = struct.pack('>Q', time_step)
	key_bytes = key.encode('utf-8')
	hmac_code = hmac.new(key_bytes, time_bytes,hashlib.sha1).digest()
	offset = hmac_code[-1] & 0x0F
	otp_unpack = struct.unpack('>I', hmac_code[offset:offset+4])[0] & 0x7FFFFFFF
	otp = str(otp_unpack % 1000000).zfill(6)
	return otp


def OTP_generator(file):
    try:
        with open(file, 'rb') as f:
            content = f.read()

        key = decrypt_key(content)
        totp = pyotp.TOTP(base64.b32encode(key.encode()))
        print("OTP CIBLE:", totp.now())

        otp = ft_generate(key)
        print("OTP GENERE:", otp)

    except FileNotFoundError:
        print(f"File {file} can't be opened")


def parse_arguments():
    parser = argparse.ArgumentParser("OTP Algorithm")
    parser.add_argument('-g', '--get_key', action="store_true", help="Get an hexadecimal key")
    parser.add_argument('-k', '--key_use', action="store_true", help="Create a password with the key")
    parser.add_argument('file', help="key file")
    return parser.parse_args()


def main():
    args = parse_arguments()

    if not args.file:
        print("Usage: ./ft_otp [OPTION] [FILE]")
    elif args.get_key is not True and args.key_use is not True:
        print("Usage: ./ft_otp [OPTION] [FILE]")
    else:
        if args.get_key is True:
            encrypt_key = parse_file(args.file)

            if encrypt_key is not None:
                with open(KEY_FILE, 'w') as file:
                    file.write(encrypt_key)
                    print("Key was successfully saved in ft_otp.key")

                if args.key_use is True:
                    OTP_generator(KEY_FILE)

        elif args.key_use is True:
            OTP_generator(args.file)


if __name__ == "__main__":
    main()