version: '3.8'

services:
  inquisitor:
    build: .
    image: inquisitor
    container_name: inquisitor
    volumes:
      - ./inquisitor:/app/inquisitor
    networks:
      - inquisitor


  server:
    image: delfer/alpine-ftp-server
    container_name: server
    ports:
      - "21000-21010:21000-21010"
    environment:
      - USERS=ffaivre|7936
    volumes:
      - ./ffaivre:/ftp/ffaivre
    networks:
      - inquisitor

  client:
    image: jlesage/filezilla
    container_name: client
    ports:
      - "5800:5800"
    volumes:
      - ./storage:/storage:rw
    networks:
      - inquisitor


networks:
  inquisitor: