#!/usr/bin/env python3


def parse_arguments():
    parser = argparse.ArgumentParser("Inquisitor")
    parser.add_argument('', help="URL targeted")
    parser.add_argument('URL', help="URL targeted")
    parser.add_argument('URL', help="URL targeted")
    parser.add_argument('URL', help="URL targeted")
    return parser.parse_args()


def main():
    args = parse_arguments()


if __name__ == "__main__":
    main()