#!/usr/bin/python3

import argparse, requests, re, os, sys, difflib, time


def test1(url, db_engine, payload):
    try:
        response = requests.get(url, params={"query": payload})
        if db_engine == "MySQL" and "MySQL error" in response.text:
            return True
        elif db_engine == "PostgreSQL" and "PostgreSQL error" in response.text:
            return True
    except requests.exceptions.RequestException:
        pass
    return False


def test2(url, payload):
    try:
        start_time = time.time()
        response = requests.get(url, params={"query": payload})
        end_time = time.time()
        if end_time - start_time > 5:
            return True
    except requests.exceptions.RequestException:
        pass
    return False


def vaccine(url, method):
    try:
        payload = "' UNION SELECT"
        test1(url, payload)
        test2(url, payload)

    except Exception as e:
        print(f"Error: {str(e)}")


def validate_args(args):
    if not args.url.startswith(('https://', 'http://')):
        args.url = 'http://' + args.url
    args.X = args.X.upper()
    if args.X != 'POST' and args.X != 'GET':
        print(f"Request type {args.X} not supported")
        sys.exit(1)


def store_results(results, filename):
    with open(filename, 'wb') as file:
        for result in results:
            file.write(result + "\n")
        print(f"Results writes in {filename}")


def parse_arguments():
    parser = argparse.ArgumentParser("Vaccine programme for testing SQL security")
    parser.add_argument('-o', type=str, default='archive.txt', help="Archive file")
    parser.add_argument('-X', type=str, default='GET', help="Type of request")
    parser.add_argument('url', help="url targeted")
    return parser.parse_args()


def main():
    global url
    args = parse_arguments()
    validate_args(args)
    url = args.url
    vaccine(url, args.X)


if __name__ == "__main__":
    main()

    